### ISSUE TITLE
Add option to provide additional functions

### ISSUE THREAD

**Issue by SvenLieber** [RMLio/rmlmapper-java-wrapper-js#15]
(Just for completeness regarding changes currently performed in the [feature/functions](https://github.com/RMLio/rmlmapper-java-wrapper-js/tree/feature/functions) branch)

The [RMLMapper](https://github.com/RMLio/rmlmapper-java#including-functions) allows to provide additional functions via the parameter `-f`. 
This is not yet implemented in the js wrapper but needed for example in https://github.com/RMLio/social-media-archiving

**Comment by pheyvaer** [comment]
Fixed via #16
