### ISSUE TITLE
Client-based mapping (question)

### ISSUE THREAD

**Issue by agamboa23** [RMLio/rmlmapper-java-wrapper-js#21]
Are there any plans for a JS based rmlmapper to enable client-based mapping?

It might be too heavy for client, but I am reviewing the possibility to allow users to map and encrypt their data on the client to prevent the server to see the plain data.

**Comment by bjdmeest** [comment]
Thanks for the answer! We're happy to point you to our https://rml.io/implementation-report/, comparing multiple RML-compliant mappers. The JS-based RMLMapper I'm aware of is https://github.com/semantifyit/RocketRML, you might find this one is suitable for your use-case :)
