### ISSUE TITLE
Allow RDFJS as input for RML mappings

### ISSUE THREAD

**Issue by julianrojas87** [RMLio/rmlmapper-java-wrapper-js#6]
The wrapper's [`execute`](https://github.com/RMLio/rmlmapper-java-wrapper-js/blob/fe3b75941390a09fbc3df8b1484de5ff1f161447/lib/wrapper.js#L29) function expects the RML mappings (`rml`) as a string:
```js
await wrapper.execute(rml, {sources, generateMetadata: false, serialization: 'turtle'});
```
However, when using this application in a pipeline together with the [yarrrml-parser](https://github.com/RMLio/yarrrml-parser), the output of the `yarrrml-parser` is an array of RDFJS quads that need to be parsed to a RDF string first, for them to be used in the wrapper. Only to be converted to RDFJS quads again [further along](https://github.com/RMLio/rmlmapper-java-wrapper-js/blob/fe3b75941390a09fbc3df8b1484de5ff1f161447/lib/wrapper.js#L179) in the mapping process.

Allowing RDFJS as input for the RML mappings would probably save some processing time in conversions.

**Comment by pheyvaer** [comment]
Good point! We will have a look at that.
